GET http://census.daybreakgames.com/get/ps2
   /item
   ?name.en=NS-11A
   &c:lang=en
   &c:join=
      fire_mode^inject_at:fire_mode^list:1,
      item_to_weapon^inject_at:fire_mode_2(
         weapon,
         weapon_to_fire_group^on:weapon_id^to:weapon_id^list:1(
            fire_group^on:fire_group_id^to:fire_group_id,
            fire_group_to_fire_mode^on:fire_group_id^to:fire_group_id^list:1(
               fire_mode_2^on:fire_mode_id^to:fire_mode_id^list:1(
                  player_state_group^list:1^inject_at:player_state_group,
                  player_state_group_2^on:player_state_group_id^to:player_state_group_id^inject_at:player_state_group_2^list:1,
                  fire_mode_to_projectile^on:fire_mode_id^to:fire_mode_id^inject_at:projectile(
                     projectile^on:projectile_id^to:projectile_id^inject_at:projectile_details
                  )
               )
            )
         )
      )
   )
   &c:join=
      weapon_datasheet^inject_at:ammo
   &c:join=
      item_category^on:item_category_id^to:item_category_id^inject_at:category
   &c:join=
      item_attachment^on:item_id^to:item_id^list:1^inject_at:attachments(
         item^on:attachment_item_id^to:item_id^inject_at:attachment(
            zone_effect^on:passive_ability_id^to:ability_id^inject_at:attachment_effects^list:1(
               zone_effect_type^on:zone_effect_type_id^to:zone_effect_type_id^inject_at:attachment_effects_description
            )
         )
      )


Accept: application/json

###

GET https://census.daybreakgames.com/get/ps2:v2/item?item_category_id=139&c:limit=100
  &c:join=item_profile^list:1^on:item_id(
    profile^list:1^on:profile_id
  )

###

GET https://census.daybreakgames.com/get/ps2:v2/

###

GET https://census.daybreakgames.com/get/ps2:v2/item?name.en=*Heavy%20Assault&c:limit=10


###

GET https://census.daybreakgames.com/get/ps2:v2/loadout?c:limit=10
   &c:join=profile^on:profile_id^to:profile_id^list:1,
   profile_resist_map^on:profile_id^to:profile_id^list:1(resist_info^on:resist_info_id^to:resist_info_id)


###

GET https://census.daybreakgames.com/get/ps2:v2/item?name.en=*Nanoweave&c:limit=100&c:lang=en
  &c:join=ability^list:1^on:activatable_ability_id^to:ability_id(
    ability_type^inject_at:ability_type_id,
    resource_type^inject_at:resource_type_id,
    effect^on:ability_id^to:ability_id^list:1(
      effect_type^inject_at:effect_type_id
    )
  ),
  ability^list:1^on:passive_ability_id^to:ability_id(
    ability_type^inject_at:ability_type_id,
    resource_type^inject_at:resource_type_id,
    effect^on:ability_id^to:ability_id^list:1(
      effect_type^inject_at:effect_type_id
    )
  ),
  item_profile^on:item_id^to:item_id^list:1(
    profile^on:profile_id^to:profile_id
  )
